# Generated by Django 2.2 on 2019-04-27 15:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(verbose_name='title')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.TextField(max_length=512, verbose_name='description')),
                ('is_start', models.BooleanField(verbose_name='is start')),
                ('is_finish', models.BooleanField(verbose_name='is finish')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='meta')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.Game')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('condition', django.contrib.postgres.fields.jsonb.JSONField(max_length=512, verbose_name='condition')),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(max_length=512, verbose_name='state')),
                ('position', models.PositiveIntegerField(verbose_name='position')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('is_visible', models.BooleanField(verbose_name='is visible')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='meta')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transitions', to='main.Location', verbose_name='source location')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transitions', to='main.Location', verbose_name='target location')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
            },
        ),
    ]
