# Generated by Django 2.2 on 2019-04-27 19:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='name',
        ),
        migrations.AlterField(
            model_name='location',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='meta'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='condition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='meta'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='state'),
        ),
    ]
