# Generated by Django 2.2 on 2019-05-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190427_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='main.Game', verbose_name='Game'),
        ),
    ]
