# Generated by Django 2.2 on 2019-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transition_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_expression_rules', models.TextField(verbose_name='bool expression rules')),
                ('state_expression_rules', models.TextField(verbose_name='state expression rules')),
            ],
            options={
                'verbose_name': 'config',
            },
        ),
    ]
