# Generated by Django 2.2 on 2019-05-22 06:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='condition_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='condition (rules)'),
        ),
        migrations.AddField(
            model_name='transition',
            name='state_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='state (rules)'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='condition',
            field=models.CharField(blank=True, max_length=1024, verbose_name='condition (readable)'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='state',
            field=models.CharField(blank=True, max_length=1024, verbose_name='state (readable)'),
        ),
    ]
