# Generated by Django 2.2 on 2019-05-22 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190522_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='initial_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='initial state (rules)'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='statement (readable)'),
        ),
    ]
