# Generated by Django 2.2 on 2019-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190522_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_finish',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_start',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Is Start'), (1, 'Is Finish')], default=0, verbose_name='type'),
        ),
    ]
